-- Script de migración a producción: INVENTARIO LÍNEA BLANCA 2026
-- Fecha de generación: 2026-09-17T02:50:16.166Z
BEGIN;

INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ALCOHOL  GEL 600 ML', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ALCOHOL  LT. 70 %', 27, 5, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ALCOHOL MEDICINAL', 6, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('AMBIENTADOR  POETT SPRAY', 53, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('AMBIENTADOR AROMATIC 300ML', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('AMBIENTADOR DE 4 LT. POET', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ARCHIVADOR DE PALANCA', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ATOMIZADOR', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('AZUCAR KG', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BARBIJOS CAJA X 50 UNID', 8, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BASURERO PEQUEÑO ROJO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BATAS IMPERMEABLES', 13, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BATAS LAVABLES CELESTES', 9, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BICARBONATO 20 GRAMOS SOBRES', 5, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLIGRAFO AZUL', 5, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLIGRAFO NEGRO', 6, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLIGRAFO ROJO', 9, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLIGRAFO VERDE BIC ROUND', 2, 4, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSA DE BASURA GRANDES P/TACHO', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSA PLASTICAS 7 X 25', 23, 5, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSA ROJA CON AGARRADOR', 77, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS  35 X 50  MANDILES (PQTE DE 100)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS  AZULES C/AGARRADOR', 16, 5, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS 13 X 25 (PQTES)', 18, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS 13 X 30', 1, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS 3X25 ESTERILIZACION', 1, 10, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS 4 X 26', 0, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS 5 X 20', 5, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS BASURA 70 X 95(PAQUETES)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS BASUREROS ROLLO ( 16X25)1000 UNID', 142, 50, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS BLANCAS 44X50 (10 UNID X PQTE)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS BLANCAS CON AGARRADOR', 33, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS C/AGARRADOR ROSA (ROLLO)', 12, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS DE BASURA NEGRAS PEQUEÑAS 50X65', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS DE BASURA ROJAS (65 X 80) PQTE DE 10', 3, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS NEGRAS CON AGARRADOR', 250, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS NEGRAS DE 140 LT X 10 UNID( 90X110)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS PEQUEÑAS NEGRAS  (60 X 90)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS PLASTICAS 16X25(PQTEX100 UNID)', 25, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS PLASTICAS 20 X 30 (LAB)', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS PLASTICAS 5 X 15 (PQTES)', 1, 5, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS ROJAS PARA TACHO GRANDE X 10 UNID', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS ZIPLOC 10 X 15  PAQUETES', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS ZIPLOC 15X 15 (PQTE)', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS ZIPLOC 15X20 PAQUETES', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS ZIPLOC 16X15  50 UNID', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS ZIPLOC 17,7X20,3 (25 UNID)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSAS ZIPLOG 5 X 6CM PQTE.', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOLSITAS PLASTICAS 5X15 (PQTES) JUAN', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOMBILLAS (PQTE.X25 UND)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BOMBRIL FINO', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('BROCHA PARA PINTURA PISO', 3, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('CARPETAS COLGANTES', 0, 5, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('CEPILLO PARA BOTELLAS BLANCOS', 8, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('CEPILLOS PEQUEÑOS', 7, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('CERA PARA PISO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('CINTA ADHESIVA', 2, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('COTONETES X CAJA', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('CORRECTOR', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('CUADERNOS', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DESATORADOR SAPOLIO 1960 ML.', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DESATORADOR SAPOLIO 960 ML', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DESINFECTANTE  OLA P/PISO 5 LT.', 6, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DESINFECTANTE IGENIX', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DESINFECTANTE IGENIX 5LT', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DESINFECTANTE LYSOFORM SPRAY', 5, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DESINFECTANTE P/PISO 2 LT. OLA', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DESINFECTANTE SAPOLIO SPRAY', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DETERGENTE 1 KG.', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DETERGENTE DE 2,3 KGR', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DIUREX (CINTA ADHESIVA PEQUEÑA)', 6, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('DULCES MENTAS', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('EMBUDO PLASTICO', 1, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ESCOBA', 5, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ESPONJA AMARILLA', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ESPONJA VERDE', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('FICHAS INGRESO 28,5 X 21,4 (1000 UNID)', 500, 50, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('FOCOS BRASILUM LARGOS', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('FOCOS DICROICOS', 6, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('FOCOS LARGOS', 4, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('FOCOS LARGOS PEQUEÑOS', 4, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('FOLDER TAMAÑO OFICIO', 30, 15, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('FRANELA NARANJA', 0, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('GASA 100 YARDAS', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('GORROS DESECHABLES MUJER', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('GOTITA', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('GUANTE DE GOMA TALLE M', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('GUANTES DE GOMA TALLA  S', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('GUANTES DE GOMA TALLA L', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('GUANTES DESECHABLES TRANSPARENTES PQTESX100UNID', 5, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('HARAGAN PLASTICO', 3, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('HOJAS BOND', 1000, 50, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('HOJAS RAYADAS', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('INCIENSO', 5, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('INSECTICIDA SIN OLOR', 3, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('INTERRUPTOR CONSULTORIOS', -5, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('JABON LIQUIDO DE 5 LT.', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('JABONCILLO', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('JABONCILLO LIQUIDO NEUTRO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('JABONCILLO LIQUIDO PEQUEÑO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('KLEENEX  DE 5O UNID.', -1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('KLEENEX 420 UNID', 16, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('KLEENEX 80 UNID.', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('KLEENEX BAMB00 100 UNID 18X19 CM C/U', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('KLEENEX JUNIOR 50 UNID', 0, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LAPICES', 7, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LAPICES CARBON', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LAVA VAJILLA', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LAVA VAJILLA DE 5 LT.', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LAVANDINA 1 LT.', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LAVANDINA 5 LT', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LAVANDINA EN POLVO SOBRES', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LAVANDINA FRSCOS DE 225 GR', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LIMPIA VIDRIOS', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LIMPIA VIDRIOS CON DESLIZADOR', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LIMPIA VIDRIOS DE 5 LT.', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LIMPIA VIDRIOS SIN GATILLO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LIMPIADOR SAPOLIO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LUBRICANTE PARA PIEZAS DE MANO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LUSTRA MUEBLES 500 ML.', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('LUSTRA MUEBLES X 250 ML', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MARCADORES DELGADOS (CONSULTORIOS)', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MARCADORES P/PIZARRA ACRILICA', 3, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MARCADORES RECEPCION', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MASCARAS TRANSPARENTES', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MASKIN DELGADO', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MASKIN GRUESO', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MATES', 1, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MICROPORE', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('MICROPORE(TRANSPARENTE)', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('NESCAFE', 1, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('OLA BRILLANTE PARA PISOS CERAMICOS', 60, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('OLA MAXIMUS ANTISARRO 550 ML.', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PAÑO MICRO FIBRA', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PAÑO PARA PISO AMARILLO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PAPEL HIGIENICO', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PAPEL HIGIENICO ROLLOS GRANDES', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PAPEL PARA CALCULADORA', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PASTILLAS AROMATIC INDORO', 7, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PASTILLAS HARPIC PARA INODORO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PASTILLAS REPELENTE MOSQUITOS OLA', 48, 4, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PILAS DURACELL  AA  PQTE X 4 UNID', 5, 4, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PILAS DURACELL AAA X PQTE 4 UNID', 6, 4, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PINTURA SPRAY PLOMA', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PLASTILINA', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PONCHILLO TIPO PELUQUERIA', 3, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PROCENEX  (DESSINFECTANTE P/PISO)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PROCENEX  900 ML.', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('PROTECTOR FACIAL', 28, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('RECETARIOS (BLOCK DE 50 UNID.)', 50, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('REPELENTE LIQUIDO SAPOLIO', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('REPUESTO TRAPEADORES', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('REPUESTOS ATOMIZADOR', 3, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('RESALTADOR', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('RODILLOS PARA PINTURA DE PISO', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('ROLLO DE BOLSAS PEQUEÑAS 16X25 (2400 UNID)', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('SAPOLIO 450 GR. FRASCO DURO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('SAPOLIO BOLSA PLASTICA 450 GR.', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('SCOTCH GRANDE', 7, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('SECADORES TELA', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('SERVILLETAS', 40, 5, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('SILICONA', 4, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('SODA CAUSTICA BOLSAS', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TALCO  200 GR.', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TAPER ESTERILIZACION  PUSH Y PUSH 550ML', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TAPERS DESECHABLES X100UNID', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TAPERS GRANDES REPUESTOS', 3, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TAPERS PEQUEÑITOS (FRESAS)', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TAPERSO PEQUEÑOS MODELOS ESTUDIO DOCENA', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TE VERDE CAJA 50 UNID', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TEE 50 UNID.', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TEFLON', 4, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TEFLON DE GAS', 5, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TIJERAS', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TOALLA BLANCA PEQUEÑA (BABERO)', 0, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TOALLA DE PAPEL PQTE X 150 HOJAS', 1, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TOALLA DE PAPEL PQTE. X200 HOJAS', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TOALLA DE PAPEL PQTE.X250 UNID', 0, 4, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TOALLA GRANDE PARA MANOS', 2, 3, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TOALLA GRANDE PARA PISO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TOALLAS BLANCAS PEQUEÑAS', 11, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TOALLAS PEQUEÑAS PARA MANOS', 4, 2, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('TRAPO PARA PISO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('VASOS DESECHABLES', 116, 50, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('VASOS DESECHABLES DE 120 ML', 0, 0, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('VASOS DESECHABLES DE 50ML PEQUEÑITOS', 1109, 100, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('VIRUTA PARA PISO', 0, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('VIRUTA VERDE (VIRUTEX)', 2, 1, 'Activo', 9, 2, NOW());
INSERT INTO inventario (descripcion, cantidad_existente, stock_minimo, estado, idespecialidad, idgrupo_inventario, created_at) VALUES ('VIRUTILLA LIQUIDA', 1, 1, 'Activo', 9, 2, NOW());

SELECT setval(pg_get_serial_sequence('inventario', 'id'), COALESCE((SELECT MAX(id) FROM inventario), 1));
COMMIT;